[theme]
base = "light"
primaryColor = "#2D4275"

[browser]
gatherUsageStats = false

[DMC]
requiredDataIdentifiers = ["P", "S|T", "V"]
UseMessageEnvelope = true
UseFormatEnvelope = true
RectangularDMC = false
NumberOfQuietZoneModuls = 2
ExplainDataIdentifiers = true